### ISSUE TITLE
Famitracker help menu segfaults on Kubuntu 22.04

### ISSUE THREAD

**Issue by Expurple** [christopherpow/nesicide#83]
Hello, I've just discovered this software and decided to try it out on my Linux machine.

Steps to reproduce:

1. Download the AppImage of [9d16ed8](https://github.com/christopherpow/nesicide/commit/9d16ed8) from [here](https://knob.phreneticappsllc.com/nesicide/?s=download) (it's only one commit behind the latest, which I'm too lazy to compile)
2. Run it
3. In the menu bar, click on `Help -> About FamiTracker...`

On my Kubuntu 22.04, the application segfaults and crashes. I'm too lazy to try this in a VM.

Stderr output:

```text
EnableHtmlHelp
SUPPORT_TRANSLATIONS
Figure out 64-bit version of these asserts...
CControlBar::SetBarStyle
QFont::setPointSize: Point size <= 0 (0), must be greater than 0
::WaitForStop()
::WaitForStop()
DSound::EnumerateDevices
RegisterSingleInstance
Segmentation fault (core dumped)
```

Segfault appears on click, the rest is printed on startup.

Backtrace in gdb (top 10 functions):

```text
#0  0x00007ffff795ab4a in CWnd::GetFont() () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#1  0x00007ffff79bdb0e in CAboutDlg::OnInitDialog() () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#2  0x00007ffff7964b05 in CDialog::DoModal() () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#3  0x00007ffff79d036f in CFamiTrackerApp::OnAppAbout() () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#4  0x00007ffff795a5b8 in CCmdTarget::OnCmdMsg(unsigned int, int, void*, AFX_CMDHANDLERINFO*) () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#5  0x00007ffff795c45a in CFrameWnd::OnCmdMsg(unsigned int, int, void*, AFX_CMDHANDLERINFO*) () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#6  0x00007ffff7979149 in CWnd::OnCommand(unsigned long, long) () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#7  0x00007ffff797811f in CWnd::OnWndMsg(unsigned int, unsigned long, long, long*) () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#8  0x00007ffff794a988 in CWnd::WindowProc(unsigned int, unsigned long, long) () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#9  0x00007ffff794b6fb in CWnd::event(QEvent*) () from /tmp/.mount_famitrAN3xP8/lib/libfamitracker.so.1
#10 0x00007ffff716058c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_famitrAN3xP8/lib/libQt5Widgets.so.5
```

Please let me know if I should provide any additional info or if you aren't going to work on this. Maybe I'll attempt it myself if I feel like it.

**Comment by christopherpow** [comment]
I can reproduce on OSX so I may have some energy to put into this. Thanks for the report.
